language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - 17
git:
  depth: 3
before_script:
  - npm install firebase-tools -g
script:
  - yarn test
  - yarn build
  - firebase deploy --only hosting --token $FIREBASE_TOKEN