language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - 17
git:
  depth: 3
before-script:
  - yarn install firebase-tool -g
script:
  - yarn test
  - yarn build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN