language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - 17
git:
  depth: 3
script:
  - yarn test
  - yarn build
deploy:
  provider: firebase
  on:
    branch: main
  edge: true
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN