language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - 17
git:
  depth: 3
script:
  - yarn test
  - yarn build
deploy:
  provider: firebase
  token:
    secure: $firebaseToken
  project: git-list